<?php
//include ("stars/new_stars_main_menu.php");

#main table of tour list
#
#
#

$direction_id=0;
//print_r($stars->array_groups);
?>
<div style='margin:auto;padding:5px' id='short-tour-list'>
    <table align='center' border='1' cellpadding='0' cellspacing='0' style='margin:auto;color:#000099;font-size:14px;font-weight:bold;padding:2px;' id="stars-list-full">

        <tr style='background:#000099;color:#fff;height:30px'>
            <td align='center'>&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td align='center'>КАТЕГОРИЯ</td>
            <td align='center'>Дни</td>
            <td align='center'>ВСТРЕЧА НОВОГО ГОДА в ТУРАХ</td>
        </tr>
<!--
<tr id='tr-stars0' style='height:50px'><td align='center'>1</td><td style='padding:0px 3px 0px 3px' class='direction_link' vol='stars0' align='center'><a href="?newyear=2012" style='color:#ff0000'><b>ВСЕ НОВОГОДНИЕ ТУРЫ СЕРИИ
ЗВЕЗДЫ АТЛАНТИКИ</b></a></td>
                        <td style='text-align:center;color:#990000;font-size:11px' >
        </td>
                        <td  style='padding:0px 3px 0px 3px;color:#ff0000' >Экскурсионные программы, которые включают праздничные даты.
        </td>
        </tr>
-->

        <tr id='tr-stars1'>
            <td align='center'>T1</td>
        <td style='padding:0px 3px 0px 3px' class='direction_link' vol='stars1' >  <!--  directon_link  -->
            <a href="#stars2"><span style="color:#ff0000">Рождество и Новый год   </span><br/><b>АТЛАНТИКА </b></a>
        </td>
        <td style='text-align:center;color:#990000;font-size:11px' >5&nbsp;-&nbsp;16
        </td>
            <td  style='padding:0px 3px 0px 3px' >Нью-Йорк, Вашингтон, Бостон, Филадельфия, Ниагарские Водопады, Ричмонд, Норфолк, Вирджиния-Бич
        </td>
        </tr>

        <tr id='tr-stars2'>
        <td align='center'>T2</td>
        <td style='padding:0px 3px 0px 3px' class='direction_link' vol='stars2' ><a href="#stars2"><span style="color:#ff0000">Рождество и Новый год   </span>
            <br/><b>ОТ ОКЕАНА ДО ОКЕАНА<br/>
            АТЛАНТИКА и ЗАПАДНОЕ ПОБЕРЕЖЬЕ США
            </b>
            </a>
        </td>

                        <td style='text-align:center;color:#990000;font-size:11px' >8&nbsp;-&nbsp;20
        </td>
                        <td  style='padding:0px 3px 0px 3px' >Лос-Анжелес, Лас-Вегас, Сан-Франциско, Сан-Диего, Заповедники, Нью-Йорк, Вашингтон, Бостон, Филадельфия, Ниагарские Водопады.
        </td>
        </tr>
        

        
        
        
        <tr id='tr-stars6' style='border-bottom:none'>
            <td align='center' class='bottom-none'>T3
            </td>
            <td style='padding:5px 3px 5px 3px'  width="40%" >
                <span style="color:#ff0000">Рождество и Новый год   </span>
                <br/>
                <span class='direction_link' vol='stars6'>
                <a href="#stars3" ><b>АТЛАНТИКА И ФЛОРИДА – Экскурсии и отдых</b></a>
                </span>
                 <!--
                <br/>
                    <a href="/stars/newyear/florida" >
                        АТЛАНТИКА И ФЛОРИДА - Экскурсионный тур
                    </a>
                    <br/>
                    <a href="/stars/?direction=florida#stars7">
                        АТЛАНТИКА И ФЛОРИДА - отдых в Майами
                    </a>
                    <br/>
                    <a href="/stars/?direction=florida#stars8">
                        АТЛАНТИКА И ФЛОРИДА - отдых в Майами и Орландо
                    </a>
                    <br/>
                    <a href="/stars/?direction=florida#stars11">
                        АТЛАНТИКА И ФЛОРИДА - туры и круизы
                    </a> -->

            </td>
            <td style='text-align:center;color:#990000;font-size:11px'  >
                5-21
            </td>
            <td    style='padding:0px 3px 0px 3px' >
                Майами, Орландо, Тампа, города Атлантики, отдых, круизы
            </td>
        </tr>

		
            <tr id='tr-stars3'>
                <td align='center'>T4</td>       <!--  directon_link  -->
                <td style='padding:0px 3px 0px 3px' class='direction_link-tmp' vol='stars3' ><a href="#stars3"> <span style="color:#ff0000">Рождество и Новый год   </span><br/>
                    <b>АТЛАНТИКА И КАНАДА</b></a></td>
                <td style='text-align:center;color:#990000;font-size:11px' >&nbsp;
                </td>

                <td  style='padding:0px 3px 0px 3px' >Монреаль, Квебек, Оттава, Торонто, Ниагарские Водопады.
                </td>
            </tr>		
		

        
        <tr id='tr-stars15'>
            <td align='center'>T5</td>
            <td style='padding:6px 3px 6px 3px' class='direction_link-tmp' vol='stars9' >       <!--  directon_link  -->
                <span style="color:#ff0000">Рождество и Новый год   </span>
                <br/>ЭКЗОТИЧЕСКИЕ ТУРЫ,включающие
                <br/><b>
                <a href="/regular/1020#costa-rika">
                ЯМАЙКУ, КОСТА-РИКУ,</a>
                 &nbsp;МЕКСИКУ,  <br/>
                <a href="/regular/hawaii-11-days#hawaii-prices">
                  ГАВАЙИ</b>
                </a>
            </td>
            <td style='text-align:center;color:#990000;font-size:11px' >&nbsp;
        </td>
                        <td  style='padding:0px 3px 0px 3px' >ЯМАЙКА, КОСТА-РИКА, МЕКСИКА,ГАВАЙИ
        </td>

        </tr>

<?php
//include ('stars/directions.phtml');



  /*


foreach ($stars_tours_directions as $directions_list) {



                        $left_menu_arr[]=$stars_tours_directions[$direction_id];
                        $direction_id_n = $direction_id+1;
                         $direction_link='stars'.$direction_id;

                        if ($direction_id == 0)  $direction_link_out = '?newyear=2012';
                        else  $direction_link_out='#stars'.$direction_id;

                        print "<tr id='tr-$direction_link'>";
                        if($direction_id==6)  {
                        print "<td align='center'
                        class='bottom-none'>$direction_id_n \n\t</td>";
                        $direction_id_n--;
                        }
                        elseif ($direction_id==7) {
                        $direction_id_n--;
                        print "<td align='center' class='bottom-none'>&nbsp; \n\t</td>";

                        }
                        elseif ($direction_id==8) {
                        print "<td align='center'>&nbsp; \n\t</td>";
                        $direction_id_n--;
                        }
                        else print "<td align='center'>$direction_id_n</td>";
                        print "<td style='padding:0px 3px 0px 3px' class='direction_link' vol='$direction_link' ><a href=\"$direction_link_out\"><b>".strip_tags($directions_list,'<span>')."</b></a></td>
                        <td style='text-align:center;color:#990000;font-size:11px' >$stars_tours_directions_days[$direction_id] \n\t</td>";
                        if ($direction_id==6){
                        print "
                        <td rowspan='3' style='padding:0px 3px 0px 3px' >$stars_tours_directions_details[$direction_id] \n\t</td>";
                        }
                        elseif($direction_id==7 or $direction_id==8 ) {}
                        else {
                        print "
                        <td  style='padding:0px 3px 0px 3px' >$stars_tours_directions_details[$direction_id] \n\t</td>";
                        }
                        print"\n\t</tr>\n\t";
                        $direction_id++;


}
*/
?>
</table></div>

