<?php

/**
 * @file
 * Contains toursdata.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function toursdata_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the toursdata module.
    case 'help.page.toursdata':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Admin Tours Data') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function toursdata_theme() {
  return [
    'toursdata' => [
      'render element' => 'children',
    ],
  ];
}
