<p id="canda-prices" class="reg-parag-head-black" style="margin: 0px;padding:10px;text-align:center;font-size:13px" id="price1">
    <span style="text-align:center;color:#000080"><b>Варианты круизов 2 января 2016 года из Порт Канаверал (Орландо)</b> </span>
</p>


<table width="95%"  align="center" border="1" style='font-size:13px;color:#000;text-align:center'  class="custom-tour-list">

     <tr style="background:#000099;color:#fff">
         <td   width=5%>Корабль</td>
         <td    width=5%>Norwegian Spirit</td>
         <td     width=5%>Carnival Valor</td>

     </tr>

          <tr class="ln1">
             <td   width='5%'>Цена с человека
									В 2-местной каюте
									инсайд   
			</td>
              
             <td   width='5%'> От  $604  <br/><span style="font-size:11px">   </span></td>
             <td   width='5%'>От  $721</td>
              
         </tr>

          <tr class="ln2">
             <td  width=5%>Цена с человека
В 2-местной каюте с окном   
 </td>
             <td   width=5%><b>От  $804 </b></td>
             <td   width=5%> От  $791 </td>

         </tr>

          <tr class="ln1">
             <td  width=5%>Цена с человека
В 2-местной каюте
 с балконом  
</td>
             <td  width=5%><b>От  $1054</b></td>
             <td   width=5%> От  $1041<br/><span style="font-size:11px">   </span></td>

         </tr>

  

</table>
<p id="canda-prices" class="reg-parag-head-black" style="margin: 0px;padding:10px;text-align:center;font-size:13px" id="price1">
    <span style="text-align:center;color:#000080"><b>Norwegian Spirit   программа круиза
</b> </span>
</p>

<table width="95%"  align="center" border="1" style='font-size:13px;color:#000;text-align:center'  class="custom-tour-list">

     <tr style="background:#000099;color:#fff">
         <td >День</td>
         <td    width=5%>Дата</td>
         <td    width=10%>Порты захода </td>
         <td    width=5%>Приб.</td>
         <td    width=5%>Отпр.</td>
     </tr>

          <tr class="ln1">
             <td   width='2%'>1 </td>
             <td   width='5%'>02.01 сб</td>
             <td   width='5%'> <b>Порт-Канаверал (США)</b></td>
             <td   width='5%'>00:00</td>
             <td   width='5%'>16:00</td>
         </tr>

           <tr class="ln2">
             <td   width='2%'>2</td>
             <td   width='5%'>03.01 вс</td>
             <td   width='5%'> <b>Нассау (Багамские о-ва))</b></td>
             <td   width='5%'>08:00</td>
             <td   width='5%'>15:00</td>
         </tr>
		 
          <tr class="ln1">
             <td   width='2%'>3 </td>
             <td   width='5%'>04.01 пн</td>
             <td   width='5%'> <b>Море (Море)</b></td>
             <td   width='5%'>00:00</td>
             <td   width='5%'>00:00</td>
         </tr>

          <tr class="ln2">
             <td   width='2%'>4 </td>
             <td   width='5%'>05.01 вт</td>
             <td   width='5%'> <b>о. Сент-Томас (Виргинские о-ва (США))</b></td>
             <td   width='5%'>11:00</td>
             <td   width='5%'>19:00</td>
         </tr>		 
		 
         <tr class="ln1">
             <td   width='2%'>5 </td>
             <td   width='5%'>06.01 ср</td>
             <td   width='5%'> <b>о. Тортола (Виргинские о-ва (Брит))</b></td>
             <td   width='5%'>08:00</td>
             <td   width='5%'>17:00</td>
         </tr>

           <tr class="ln2">
             <td   width='2%'>6 </td>
             <td   width='5%'>07.01 чт</td>
             <td   width='5%'> <b>Море (Море)</b></td>
             <td   width='5%'>00:00</td>
             <td   width='5%'>00:00</td>
         </tr>
		 
          <tr class="ln1">
             <td   width='2%'>7 </td>
             <td   width='5%'>08.01 пт</td>
             <td   width='5%'> <b>Море (Море)</b></td>
             <td   width='5%'>00:00</td>
             <td   width='5%'>10:00</td>
         </tr>

          <tr class="ln2">
             <td   width='2%'>8 </td>
             <td   width='5%'>09.01 сб</td>
             <td   width='5%'> <b>Порт-Канаверал (США)</b></td>
             <td   width='5%'>08:00</td>
             <td   width='5%'>00:00</td>
         </tr>			 

</table>



<p id="canda-prices" class="reg-parag-head-black" style="margin: 0px;padding:10px;text-align:center;font-size:13px" id="price1">
    <span style="text-align:center;color:#000080"><b>Carnival Valor    программа круиза
</b> </span>
</p>

<table width="95%"  align="center" border="1" style='font-size:13px;color:#000;text-align:center'  class="custom-tour-list">

     <tr style="background:#000099;color:#fff">
         <td  >День</td>
         
         <td   width=10%>Порт</td>
         <td    width=5%>C</td>
         <td    width=5%>До</td>
     </tr>

          <tr class="ln1">
             <td   width='2%'>1 </td>
           
             <td   width='5%'> <b>Порт-Канаверал (США)<br/>Отправление</b></td>
             <td   width='5%'> </td>
             <td   width='5%'>16:00</td>
         </tr>

           <tr class="ln2">
             <td   width='2%'>2</td>
             
             <td   width='5%'> <b>В плавании</b></td>
             <td   width='5%'> </td>
             <td   width='5%'> </td>
         </tr>
		 
          <tr class="ln1">
             <td   width='2%'>3 </td>
            
             <td   width='5%'> <b>о. Косумель, Мексика </b></td>
             <td   width='5%'>10:00</td>
             <td   width='5%'>18:00</td>
         </tr>

          <tr class="ln2">
             <td   width='2%'>4 </td>
             
             <td   width='5%'> <b>Белиз, Белиз </b></td>
             <td   width='5%'>08:00</td>
             <td   width='5%'>17:00</td>
         </tr>		 
		 
         <tr class="ln1">
             <td   width='2%'>5 </td>
             
             <td   width='5%'> <b>Махогани Бей, Гондурас </b></td>
             <td   width='5%'>09:00</td>
             <td   width='5%'>18:00</td>
         </tr>

           <tr class="ln2">
             <td   width='2%'>6 </td>
            
             <td   width='5%'> <b>Коста-Майя, Мексика </b></td>
             <td   width='5%'>07:00</td>
             <td   width='5%'>14:00</td>
         </tr>
		 
          <tr class="ln1">
             <td   width='2%'>7 </td>
             
             <td   width='5%'> <b>В плавании</b></td>
             <td   width='5%'>   </td>
             <td   width='5%'>   </td>
         </tr>

          <tr class="ln2">
             <td   width='2%'>8 </td>
             
             <td   width='5%'> <b>Порт Канаверал, США <br/>Прибытие
</b></td>
             <td   width='5%'>08:00</td>
             <td   width='5%'>  </td>
         </tr>			 

</table>
