<p id="canda-prices" class="reg-parag-head-black" style="margin: 0px;padding:10px;text-align:center;font-size:13px" id="price1">
    <span style="text-align:center;color:#000080"><b>РАСЦЕНКИ НА ТУРЫ <br/>по КАНАДЕ</b> </span>
</p>

<table width="95%"  align="center" border="1" style='font-size:13px;color:#000;text-align:center'  class="custom-tour-list">

     <tr >
         <td  class='header' width=5%>НАЗВАНИЕ ТУРА</td>
         <td  class='header'width=5%>ДНЕЙ</td>
         <td  class='header' width=5%>ЦЕНА на 1 чел <br/>при 2-местном размещении </td>
         <td  class='header' width=5%>Доплата за 1-местное размещение (сингл)</td>
         <td  class='header' width=5%>СКИДКА с 3-го и 4-го <br/>при проживании 3-х или 4-х в номере </td>
     </tr>

          <tr class="ln1">
             <td   width='5%'>Французcкая Канада </td>
             <td   width='5%'><b>3 дня</b></td>
             <td   width='5%'> $410 <br/><span style="font-size:11px">   </span></td>
             <td   width='5%'>$45 в ночь</td>
             <td   width='5%'>25%</td>
         </tr>

          <tr class="ln2">
             <td  width=5%>Английская Канада </td>
             <td   width=5%><b>3 дня</b></td>
             <td   width=5%> $410 <br/><span style="font-size:11px">   </span></td>
             <td   width=5%>$45 в ночь</td>
             <td   width=5%>25%</td>
         </tr>

          <tr class="ln1">
             <td  width=5%>Канада Французкая и Оттава</td>
             <td  width=5%><b>4 дня</b></td>
             <td   width=5%> $580 <br/><span style="font-size:11px">   </span></td>
             <td   width=5%>$45 в ночь</td>
             <td   width=5%>25%</td>
         </tr>

          <tr class="ln2">
             <td  width=5%>Канада Большой Тур</td>
             <td  width=5%><b>5 дней</b></td>
             <td   width=5%> $745 <br/><span style="font-size:11px">   </span></td>
             <td   width=5%>$45 в ночь</td>
             <td   width=5%>25%</td>
         </tr>

          <tr class="ln1">
             <td  width=5%>Лучшее в Канаде </td>
             <td  width=5%><b>6 дней</b></td>
             <td   width=5%> $890 <br/><span style="font-size:11px">   </span></td>
             <td   width=5%>$45 в ночь</td>
             <td   width=5%>25%</td>
         </tr>

          <tr class="ln2">
             <td   width=5%>Атлантическая Канада  </td>
             <td   width=5%><b>8 дней</b></td>
             <td   width=5%> $1170 <br/><span style="font-size:11px"> + перелет  </span></td>
             <td   width=5%>$45 в ночь</td>
             <td   width=5%>25%</td>
         </tr>

</table>
