<div style='margin:auto;padding:5px' id='short-tour-list'>
<table align='center' id='atlantica-florida' border='1' cellpadding='0' cellspacing='0' style='margin:auto;color:#000099;font-size:1.2em;font-weight:bold;'>
<tr style='background:#000099;color:#fff'>
<td align='center'>&nbsp;</td>
<td align='center'>КАТЕГОРИЯ</td>
<td align='center'>&nbsp;Дни&nbsp;</td>
<td align='center'>&nbsp;Главные достопримечательности, города и штаты&nbsp;</td>
</tr>

    <tr id='tr-stars6' style='border-bottom:none;'>
        <td align='center' >
            &nbsp;1&nbsp;
        </td>
        <td style='padding:5px 3px 5px 3px' class='direction_link ' vol='stars6' >
            <a href="#short-tour-list"><b>АТЛАНТИКА И ФЛОРИДА - Экскурсионный тур</b></a>
        </td>

        <td style='text-align:center;color:#990000;font-size:11px' rowspan='3'>
        </td>
        <td rowspan='3' style='padding:5px 3px 5px 3px' >
            Майами, Орландо, Тампа, города Атлантики, отдых, круизы
        </td>
    </tr>
    <tr id='tr-stars7' style='border-bottom:none;border-top:none;'>
        <td align='center' class=' top-none'>
            &nbsp;2&nbsp;
        </td>
        <td style='padding:4px 3px 4px 3px' class='direction_link  top-none' vol='stars7' >
            <a href="#short-tour-list"><b>АТЛАНТИКА И ФЛОРИДА - отдых в Майами</b></a>
        </td>
    </tr>

    <tr id='tr-stars8'>
        <td align='center' class='top-none'>
            &nbsp;3&nbsp;
        </td>
        <td style='padding:5px 3px 5px 3px' class='direction_link  top-none' vol='stars8' >
            <a href="#short-tour-list"><b>АТЛАНТИКА И ФЛОРИДА - отдых в Майами и Орландо</b></a>
        </td>
    </tr>
    <tr id='tr-stars11'>
        <td align='center' class='top-none'>
            &nbsp;4&nbsp;
        </td>
        <td style='padding:5px 3px 5px 3px' class='direction_link bottom-none top-none' vol='stars11' >
            <a href="#short-tour-list"><b>АТЛАНТИКА и солнечная ФЛОРИДА с Карибским круизом</b></a>
        </td>
        <td style='text-align:center;color:#990000;font-size:11px'> 16
        </td>
        <td style='padding:5px 3px 5px 3px'><a href="/regular/Atlantic-NewYork-Florida-Cruise#description"> Нью-Йорк, Орландо, Майами, Карибский круиз </a>
        </td>
        
    </tr>
</table>
</div>
<div style='text-align:left;margin:2px 15px 5px 50px'>
    <a href='/stars/#short-tour-list' style='text-decoration:underline;font-size:15px;color:#000099'><b>Вернуться к турам  "Звезды Атлантики" >> </b></a>
</div>
