<?php

/*

Different array for different cases



First array is a existing array for regular stars tour on Oct 27 2011

second array for newyear 2012

there are

        direction - name of direction

        link      - link to detailed table. If need link to not exisiting table insert unexisting number

        days      - days remark

        details   - detail description



*/

$stars_tours_directions = array();

$stars_tours_directions[] =

'ВСЕ НОВОГОДНИЕ ТУРЫ СЕРИИ

ЗВЕЗДЫ АТЛАНТИКИ';



$stars_tours_directions[] = 'АТЛАНТИКА';

$stars_tours_directions[] = 'АТЛАНТИКА и ЗАПАДНОЕ ПОБЕРЕЖЬЕ США - ДВА ОКЕАНА';

$stars_tours_directions[] = 'АТЛАНТИКА И КАНАДА';

$stars_tours_directions[] = 'ВСЯ КАНАДА - ВОСТОК И ЗАПАД';

$stars_tours_directions[] = 'КАНАДА <span style="color:#990000">(без заезда в США)</span>';

$stars_tours_directions[] = 'АТЛАНТИКА И ФЛОРИДА - Экскурсионный тур';

$stars_tours_directions[] = 'АТЛАНТИКА И ФЛОРИДА - отдых в Майами';

$stars_tours_directions[] = 'АТЛАНТИКА И ФЛОРИДА - отдых в Майами и Орландо';

$stars_tours_directions[] = 'КАНАДА и ФЛОРИДА';

$stars_tours_directions[] = 'АТЛАНТИКА И СРЕДНИЙ ЗАПАД (АТЛАНТИКА-ЧИКАГО)';

$stars_tours_directions[] = 'ГРАНД-ТУРЫ: АЛЯСКА, ЗАПАДНАЯ КАНАДА, КАЛИФОРНИЯ, ГАВАЙИ';

$stars_tours_directions[] = 'ЭКЗОТИЧЕСКИЕ ТУРЫ, включающие ЯМАЙКУ, КОСТА-РИКУ, МЕКСИКУ';



$stars_tours_directions_days[] = '';

$stars_tours_directions_days[] = '5&nbsp;-&nbsp;12';

$stars_tours_directions_days[] = '8&nbsp;-&nbsp;19';

$stars_tours_directions_days[] = '';

$stars_tours_directions_days[] = '';

$stars_tours_directions_days[] = '';

$stars_tours_directions_days[] = '';

$stars_tours_directions_days[] = '';

$stars_tours_directions_days[] = '';

$stars_tours_directions_days[] = '';

$stars_tours_directions_days[] = '';

$stars_tours_directions_days[] = '15&nbsp;-&nbsp;28';

$stars_tours_directions_days[] = '';



$stars_tours_directions_details[] = 'Экскурсионные программы, которые включают праздничные даты. ';

$stars_tours_directions_details[] = 'Нью-Йорк, Вашингтон, Бостон, Ниагарские Водопады';

$stars_tours_directions_details[] = 'Лос-Анжелес, Лас-Вегас, Сан-Франциско, Сан-Диего, Заповедники';

$stars_tours_directions_details[] = 'Монреаль, Квебек, Оттава, Торонто, Ниагарские Водопады';

$stars_tours_directions_details[] = 'Ванкувер, Эдмонтон, Калгари, Заповедники';

$stars_tours_directions_details[] = 'Монреаль, Квебек, Оттава, Торонто, Ниагарские Водопады Ванкувер, Эдмонтон, Калгари, Заповедники';

$stars_tours_directions_details[] = 'Майами, Орландо, Тампа, города Атлантики, отдых, круизы';

$stars_tours_directions_details[] = 'Майами, Орландо, Тампа, города Атлантики, отдых, круизы';

$stars_tours_directions_details[] = 'Майами, Орландо, Тампа, города Атлантики, отдых, круизы';

$stars_tours_directions_details[] = 'Майами, Орландо, Тампа, города Атлантики, города Канады';

$stars_tours_directions_details[] = 'Чикаго и города Атлантики';

$stars_tours_directions_details[] = 'АЛЯСКА, ЗАПАДНАЯ КАНАДА, КАЛИФОРНИЯ, ГАВАЙИ';

$stars_tours_directions_details[] = 'Ямайка, Коста-Рика, Мексика';





$stars_tours_directions_newyear[0]['direction'] = '';

$stars_tours_directions_newyear[1]['direction'] = 'АТЛАНТИКА';

$stars_tours_directions_newyear[2]['direction'] = 'АТЛАНТИКА и ЗАПАДНОЕ ПОБЕРЕЖЬЕ США - ДВА ОКЕАНА';

$stars_tours_directions_newyear[3]['direction'] = 'АТЛАНТИКА И КАНАДА';

$stars_tours_directions_newyear[4]['direction'] = 'ВСЯ КАНАДА - ВОСТОК И ЗАПАД';

$stars_tours_directions_newyear[5]['direction'] = 'КАНАДА <span style="color:#990000">(без заезда в США)</span>';

$stars_tours_directions_newyear[6]['direction'] = 'АТЛАНТИКА И ФЛОРИДА - Экскурсионный тур';

$stars_tours_directions_newyear[7]['direction'] = 'АТЛАНТИКА И ФЛОРИДА - отдых в Майами';

$stars_tours_directions_newyear[8]['direction'] = 'АТЛАНТИКА И ФЛОРИДА - отдых в Майами и Орландо';

$stars_tours_directions_newyear[9]['direction'] = 'АТЛАНТИКА И ФЛОРИДА - туры и круизы ';

$stars_tours_directions_newyear[10]['direction'] = 'ЭКЗОТИЧЕСКИЕ ТУРЫ, включающие ЯМАЙКУ, КОСТА-РИКУ, МЕКСИКУ';



$stars_tours_directions_newyear[0]['link'] =0;

$stars_tours_directions_newyear[1]['link'] =1;

$stars_tours_directions_newyear[2]['link'] =2;

$stars_tours_directions_newyear[3]['link'] =3;

$stars_tours_directions_newyear[4]['link'] =4;

$stars_tours_directions_newyear[5]['link'] =5;

$stars_tours_directions_newyear[6]['link'] =6;

$stars_tours_directions_newyear[7]['link'] =7;

$stars_tours_directions_newyear[8]['link'] =8;

$stars_tours_directions_newyear[9]['link'] =12;

$stars_tours_directions_newyear[10]['link'] ='/new-tours/regular.php?reg_id=1020#costa-rika';



$stars_tours_directions_newyear[0]['days'] ='';

$stars_tours_directions_newyear[1]['days'] ='5&nbsp;-&nbsp;12';

$stars_tours_directions_newyear[2]['days'] ='8&nbsp;-&nbsp;19';

$stars_tours_directions_newyear[3]['days'] ='';

$stars_tours_directions_newyear[4]['days'] ='';

$stars_tours_directions_newyear[5]['days'] ='';

$stars_tours_directions_newyear[6]['days'] ='';

$stars_tours_directions_newyear[7]['days'] ='';

$stars_tours_directions_newyear[8]['days'] ='';

$stars_tours_directions_newyear[9]['days'] ='';

$stars_tours_directions_newyear[10]['days'] ='';



$stars_tours_directions_newyear[0]['details'] = '';

$stars_tours_directions_newyear[1]['details'] = 'Нью-Йорк, Вашингтон, Бостон, Ниагарские Водопады';

$stars_tours_directions_newyear[2]['details'] = 'Лос-Анжелес, Лас-Вегас, Сан-Франциско, Сан-Диего, Заповедники';

$stars_tours_directions_newyear[3]['details'] = 'Монреаль, Квебек, Оттава, Торонто, Ниагарские Водопады';

$stars_tours_directions_newyear[4]['details'] = 'Ванкувер, Эдмонтон, Калгари, Заповедники';

$stars_tours_directions_newyear[5]['details'] = 'Монреаль, Квебек, Оттава, Торонто, Ниагарские Водопады';

$stars_tours_directions_newyear[6]['details'] = 'Майами, Орландо, Тампа, города Атлантики, города Канады';

$stars_tours_directions_newyear[7]['details'] = 'Майами, Орландо, Тампа, города Атлантики, города Канады';

$stars_tours_directions_newyear[8]['details'] = 'Майами, Орландо, Тампа, города Атлантики, города Канады';

$stars_tours_directions_newyear[9]['details'] = 'Майами, Орландо, Тампа, города Атлантики, города Канады';

$stars_tours_directions_newyear[10]['details'] = 'Ямайка, Коста-Рика, Мексика';





$stars_tours_directions_days_newyear[] = '';

$stars_tours_directions_days_newyear[] = '5&nbsp;-&nbsp;12';

$stars_tours_directions_days_newyear[] = '8&nbsp;-&nbsp;19';

$stars_tours_directions_days_newyear[] = '';

$stars_tours_directions_days_newyear[] = '';

$stars_tours_directions_days_newyear[] = '';

$stars_tours_directions_days_newyear[] = '';

$stars_tours_directions_days_newyear[] = '';

$stars_tours_directions_days_newyear[] = '';

$stars_tours_directions_days_newyear[] = '';

$stars_tours_directions_days_newyear[] = '';



$stars_tours_directions_details_newyear[] = '';

$stars_tours_directions_details_newyear[] = 'Нью-Йорк, Вашингтон, Бостон, Ниагарские Водопады';

$stars_tours_directions_details_newyear[] = 'Лос-Анжелес, Лас-Вегас, Сан-Франциско, Сан-Диего, Заповедники';

$stars_tours_directions_details_newyear[] = 'Монреаль, Квебек, Оттава, Торонто, Ниагарские Водопады';

$stars_tours_directions_details_newyear[] = 'Ванкувер, Эдмонтон, Калгари, Заповедники';

$stars_tours_directions_details_newyear[] = 'Монреаль, Квебек, Оттава, Торонто, Ниагарские Водопады';

$stars_tours_directions_details_newyear[] = 'Майами, Орландо, Тампа, города Атлантики, города Канада';

$stars_tours_directions_details_newyear[] = 'Майами, Орландо, Тампа, города Атлантики, города Канада';

$stars_tours_directions_details_newyear[] = 'Майами, Орландо, Тампа, города Атлантики, города Канада';

$stars_tours_directions_details_newyear[] = 'Майами, Орландо, Тампа, города Атлантики, города Канада';

$stars_tours_directions_details_newyear[] = 'ЯМАЙКА, КОСТА-РИКА, МЕКСИКА';





