<table align='center' border='1' cellpadding='0' cellspacing='0' style='margin:auto;color:#000099;font-size:1.2em;font-weight:bold;background:#eeeeee'>
    <tr style='background:#000099 url(../newyear/images/backgr/snow_bg1.png);color:#ffccff;height:50px;font-size:16px'>
        <td align='center'>&nbsp;</td>
        <td align='center' style='font-size:22px'><b>КАТЕГОРИЯ</b></td>
        <td align='center' style='padding:3px'>Дни</td>
        <td align='center'>Главные достопримечательности, города и штаты</td>
    </tr>
    <tr id='tr-stars1' class='row-ny2'>
                        <td align='center'>1</td>
                        <td align='center' style='padding:0px 3px 0px 3px' class='direction_link' vol='stars1' ><a href="#stars1"><b>НОВОГОДНИЕ ТУРЫ <br/>АТЛАНТИКА</b></a></td>
                        <td style='text-align:center;color:#990000;font-size:11px' >5&nbsp;-&nbsp;12</td>
                        <td  style='padding:0px 3px 0px 3px' >Нью-Йорк, Вашингтон, Бостон, Ниагарские Водопады</td>
    </tr>
    <tr id='tr-stars2' class='row-ny1'>
                        <td align='center'>2</td>
                        <td align='center' style='padding:0px 3px 0px 3px' class='direction_link' vol='stars2' ><a href="#stars2"><b>НОВОГОДНИЕ ТУРЫ <br/>ВОСТОК-ЗАПАД США <br/>АТЛАНТИКА и ЗАПАДНОЕ ПОБЕРЕЖЬЕ США - ДВА ОКЕАНА</b></a></td>
                        <td style='text-align:center;color:#990000;font-size:11px' >8&nbsp;-&nbsp;19</td>
                        <td  style='padding:0px 3px 0px 3px' >Лос-Анжелес, Лас-Вегас, Сан-Франциско, Сан-Диего, Заповедники</td>
    </tr>
    <tr id='tr-stars3' class='row-ny2'>
                        <td align='center'>3</td>
                        <td align='center' style='padding:0px 3px 0px 3px' class='direction_link' vol='stars3' ><a href="#stars3"><b>НОВОГОДНИЕ ТУРЫ <br/>КАНАДА <br/>США КАНАДА</b></a></td>
                        <td style='text-align:center;color:#990000;font-size:11px' >8-15</td>
                        <td  style='padding:0px 3px 0px 3px' >Монреаль, Квебек, Оттава, Торонто, Ниагарские Водопады</td>
    </tr>
    <tr id='tr-stars7' class='row-ny1'>
                        <td align='center'>4</td>
                        <td align='center' style='padding:0px 3px 0px 3px' class='direction_link' vol='stars7' >
                            <b>НОВОГОДНИЕ ТУРЫ<br/>ФЛОРИДА</b>
                            <p>АТЛАНТИКА И ФЛОРИДА - Экскурсионный тур</p>
                            <p>АТЛАНТИКА И ФЛОРИДА - отдых в Майами </p>
                            <p>АТЛАНТИКА И ФЛОРИДА - отдых в Майами и Орландо</p>
                            <p>АТЛАНТИКА И ФЛОРИДА - туры и круизы</p>
                        </td>
                        <td style='text-align:center;color:#990000;font-size:11px' ></td>
                                <td  style='padding:0px 3px 0px 3px' >Майами, Орландо, Тампа, города Атлантики, города Канады</td>
    </tr>
    <tr id='tr-stars/new-tours/regular.php?reg_id=1020#costa-rika' class='row-ny2'>
                        <td align='center'>5</td>
                        <td align='center' style='padding:0px 3px 0px 3px' class='direction_link' vol='stars/new-tours/regular.php?reg_id=1020#costa-rika' >
                        <a href="/new-tours/regular.php?reg_id=1020#costa-rika"><b>ЭКЗОТИЧЕСКИЕ НОВОГОДНИЕ ТУРЫ
                                ЯМАЙКА, КОСТА-РИКА, МЕКСИКА, ГАВАЙИ
                        </b></a>
                        </td>
                        <td style='text-align:center;color:#990000;font-size:11px' > 8-21 </td>
                        <td  style='padding:0px 3px 0px 3px' >Ямайка, Коста-Рика, Мексика</td>
    </tr>
    <tr id='tr-stars/new-tours/regular.php?reg_id=1020#costa-rika' class='row-ny2'>
                        <td align='center'>6</td>
                        <td align='center' style='padding:0px 3px 0px 3px' class='direction_link' vol='stars/new-tours/regular.php?reg_id=1020#costa-rika' >
                        <a href="/new-tours/regular.php?reg_id=1020#costa-rika"><b>РЕГУЛЯРНЫЕ ТУРЫ
                                            <br/>В Новогодние даты</b></a>
                        </td>
                        <td style='text-align:center;color:#990000;font-size:11px' > 1-15 </td>
                        <td  style='padding:0px 3px 0px 3px' > </td>
    </tr>

</table>
