<?php

/**
 * @file
 * Contains tours.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tours_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tours module.
    case 'help.page.tours':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Main module to manage tours Dand output') . '</p>';
      return $output;

    default:
  }
}

function tours_theme($existing, $type, $theme, $path) {
  return array(
    'tours_list' => [
        'variables' => [
            'tours_data'=>NULL,
            'empty_data' => NULL,
            'dates_data'=>NULL,
            'price_data'=>NULL,
            'header'=> NULL,
            'table_title'=> NULL
        ],

    ],
    'carousels_list' => [
        'variables' => [
            'tours_data'=>NULL,
            'empty_data' => NULL,
            'dates_data'=>NULL,
            'price_data'=>NULL,
            'header'=> NULL,
            'table_title'=> NULL
        ],

    ],
      'wishlist_carousel' => [
          
      ],
      'index_list' =>[

    ]
  );
}
