<?php

/**
 * @file
 * Contains tours.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tours_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tours module.
    case 'help.page.tours':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Main module to manage tours Dand output') . '</p>';
      return $output;

    default:
  }
}

function tourst_twig_theme($existing, $type, $theme, $path) {
  return array(
    'tours_list' => array(
      'variables' => array('tour_list' => NULL),
    ),
      'wishlist_carousel' => [
          
      ]
  );
}
